### PR TITLE
added documentation for /schedule/week endpoint

### PR DESCRIPTION
**Pull request by ileenf**
## Reference Issues
#192 

## Summary of Change/Fix 
Added documentation for the /schedule/week endpoint for Schedule of Classes REST API. Includes parameter descriptions and sample responses. Added documentation for Graphql API for /schedule/week endpoint.

## Test Plan
Run locally to ensure /schedule/week documentation is listed under REST API -> Schedule of Classes.

### CODE REVIEW

**Review by ramanxg — CHANGES_REQUESTED** [review]
image

Can you fix this example? I think the response should be inside the green collapsible.

**Comment by ileenf** [comment]
Fixed and added some changes to GraphQL api! Let me know if there's anything else I should add.

**Review by ramanxg — COMMENTED** [review]
Just one more thing, in the learn more page, change 
"Our API has 6 queries you can use to make a request for data."

"Our API has ~~6~~ 7 queries you can use to make a request for data."

**Review by ramanxg — APPROVED** [review]

**Comment by ramanxg** [comment]
LGTM!

**Pull request merged**
